//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondDay.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderInParty = new HashSet<OrderInParty>();
        }
    
        public int ID { get; set; }
        public int SenderID { get; set; }
        public int ConsigneeID { get; set; }
        public Nullable<decimal> PartyCustomValue { get; set; }
        public Nullable<int> Number { get; set; }
        public string Shipment { get; set; }
        public decimal DeclareValue { get; set; }
        public int UnitID { get; set; }
        public decimal InsureValue { get; set; }
        public int DestinationCityID { get; set; }
        public int OriginCityID { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Cities Cities1 { get; set; }
        public virtual Costumers Costumers { get; set; }
        public virtual Costumers Costumers1 { get; set; }
        public virtual Party Party { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInParty> OrderInParty { get; set; }
    }
}
