//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondDay.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortsInRout
    {
        public int ID { get; set; }
        public int RoutID { get; set; }
        public int PortID { get; set; }
        public int PriorityInRout { get; set; }
    
        public virtual Ports Ports { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
